;v10 مشکل license release رو هم برطرف می‌کنه.

; همه‌ی WinWaitActiveها می‌تونن یه Return دااشته باشن و از اونا بایذ استفاده بشه. بهتره که استفاده بشه.
; همینطور ControlClick و Send که می‌تونه با ControlSend جایگزین بشه
;اسم قطعات مثل خازن‌ها و ... به هیچ‌وجه نباید فاصله درش داشته باشه

#RequireAdmin
#include <MsgBoxConstants.au3>
#include <StringConstants.au3>
#include <File.au3>
#include <Array.au3>
#include <String.au3>
#Include <Date.au3>

;;;;;;;;;;;;; DEFINING MAIN CONTROLS ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Global Const $debuging_mode = False								;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
$do_cst_simulation = False										;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
$close_LTSpice_at_finish = True									;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
$detect_and_resolve_license_release = True						;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
$draw_load_resistance = True									;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
$use_constant_values = False									;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
$AC_analysis = False											;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
$bahraami_coefficient = False									;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
$draw_both_c_f = True											;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
$draw_center_trapped_transformer = True							;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
$power_down_after_run = True									;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
$give_origin_dat_file_instead_of_voltage_and_current = False	;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;;;;;;;;;; BAHRAAMI'S COEFFICIENT ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
$bahraami_c_se_coef = 0.959665106
$bahraami_c_ac_r_coef = 1.276620619
$bahraami_c_ac_l_coef = 1.318559758
$bahraami_c_cc_coef = 1.4770
$bahraami_c_f_coef = 1.1666
$bahraami_c_crona_terminal_coef = 1.3426
$bahraami_c_terminal_container_coef = 1.4278
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

Local $tray_messages_array[9] = ["", "", "", "", "", "", ""]; making an empty array for tray messages

;;;;;;;;;;;;;; Getting DATEANDTIME for further uses ;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
$DateStr = _Date_Time_GetLocalTime();;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
$DateStr = _Date_Time_SystemTimeToDateTimeStr($DateStr, 1);;;;;;;;;;;;;;
$DateStr = StringReplace($DateStr , " ", "");;;;;;;;;;;;;;;;;;;;;;;;;;;;
$DateStr = StringReplace($DateStr , "/", "");;;;;;;;;;;;;;;;;;;;;;;;;;;;
$DateStr = StringReplace($DateStr , ":", "");;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;; Needed for detecting and holding errors globally ;;;;;;;;
$error_encoutrance = False;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

If Not $use_constant_values Then
   Tray_Messages_Push('•  Getting Input (.cst)')
   $browse_title = "Open the CST File:"
   Global $input_multipile_cstfile = FileOpenDialog($browse_title, "E:\CST training.cst\", "CST Project Files (*.cst)", 1 + 4 )
   $inputcstfile_array = StringSplit($input_multipile_cstfile, "|")
   If $debuging_mode Then																									; Codes to run MULTIPLE files
	_ArrayDisplay($inputcstfile_array, "[get_cst_files] The opened files array")											; Codes to run MULTIPLE files
			   MsgBox(262176,"[TrayTip] Array UBound", UBound($inputcstfile_array) ,10)									; Codes to run MULTIPLE files
   EndIf																													; Codes to run MULTIPLE files
				  If UBound($inputcstfile_array) = 2 Then																	; Codes to run MULTIPLE files
					 $file_array_starting_point = 1																		; Codes to run MULTIPLE files
				  Else																										; Codes to run MULTIPLE files
					 $file_array_starting_point =2																			; Codes to run MULTIPLE files
				  EndIf																									; Codes to run MULTIPLE files
EndIf
If $use_constant_values Then
   $file_array_starting_point = 0
   Global $inputcstfile_array[1] = [""]
   $cst_project_file_name = 'autogenerated'
EndIf
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
						For $file_numerator= $file_array_starting_point To UBound($inputcstfile_array) - 1;;;;;;;;;;;;;;; Codes to run MULTIPLE files;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
If Not $use_constant_values Then
		   If UBound($inputcstfile_array) = 2 Then																			; Codes to run MULTIPLE files
			   $inputcstfile = $inputcstfile_array[1]																		; Codes to run MULTIPLE files
				  If $debuging_mode Then																					; Codes to run MULTIPLE files
				  MsgBox(262176,'[get_cst_files] file number: ' & $file_numerator, $inputcstfile ,5)						; Codes to run MULTIPLE files
				  EndIf																									; Codes to run MULTIPLE files
		   ElseIf UBound($inputcstfile_array) > 2 Then																		; Codes to run MULTIPLE files
			   $inputcstfile = $inputcstfile_array[1] & "\" & $inputcstfile_array[$file_numerator]							; Codes to run MULTIPLE files
				  If $debuging_mode Then																					; Codes to run MULTIPLE files
				  MsgBox(262176,'[get_cst_files] file number: ' & $file_numerator, $inputcstfile ,5)						; Codes to run MULTIPLE files
				  EndIf																									; Codes to run MULTIPLE files
		   Else																											; Codes to run MULTIPLE files
			   MsgBox(262176,$file_numerator, "[get_cst_files] Logical Error on opening CST Studio File (.cst)!",10)		; Codes to run MULTIPLE files
		   EndIf

   ;If $debuging_mode Then
   ;   $inputcstfile = "E:\CST training.cst\17th.try.1396060121254.example_for_coupling.cst"
   ;ElseIf Not $debuging_mode Then
   ;   Global $inputcstfile = FileOpenDialog($browse_title, "E:\CST training.cst\", "CST Project Files (*.cst)", 1 + 4 )
   ;EndIf
   If $debuging_mode Then
		   MsgBox(262176,"[get_cst_files] The Input CST file location", $inputcstfile,10)
   EndIf
   Local $cst_project_drive = "", $cst_project_dir = "", $cst_project_file_name = "", $cst_extention = ""
   _PathSplit($inputcstfile,$cst_project_drive,$cst_project_dir,$cst_project_file_name,$cst_extention)
   If $debuging_mode Then
		   MsgBox(262176,"[get_cst_files] The Input CST file Name", $cst_project_file_name,10)
   EndIf
   ; $inputcstfile = 'E:\CST training.cst\17th.try.1396060121254.example_for_coupling.cst'
   Global $cstextension = '.cst'
   Global $capacitance_output_file = 'capacitance_file_output.capacitance'

   ;;;;;;;;;; OPEN THE CST PROJECT FILE ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
   If StringInStr(StringRight($inputcstfile, 4), $cstextension) Then
	   $cstfolder = StringReplace($inputcstfile, $cstextension, "" , -1)
   Else
	   MsgBox(262160, "[get_cst_files] Error", "This is not a CST file or there is something wrong with the file!",20)
	   ContinueLoop
   EndIf

   Global $par_file_lines
   Tray_Messages_Push('•  Reading .par File')
	   If Not _FileReadToArray($cstfolder & '\Model\Parameters.json', $par_file_lines) Then
		   MsgBox(262160, "[par] " & $cst_project_file_name, "There was an error reading the Parameters (Model.par) file. @error: " & @error , 20) ; An error occurred reading the current script file.
		   ContinueLoop
	   EndIf

   If $debuging_mode Then
   MsgBox(262176, "[par] Number of Lines", $par_file_lines[0] ,10)
   EndIf
   For $i = $par_file_lines[0] To 1 Step -1
   $par_file_lines[$i] = StringStripWS($par_file_lines[$i], $STR_STRIPLEADING + $STR_STRIPTRAILING + $STR_STRIPSPACES)
		If $par_file_lines[$i] = '"name": "number_of_stages",' Then
			$column_n = StringTrimRight(StringReplace($par_file_lines[$i+1], '"value": "', ""),1)
			If $debuging_mode Then
			MsgBox(262176, "[n] " & $cst_project_file_name, "The number of repetition for columns is " & $column_n, 10)
			EndIf
		EndIf

   Next
   If $debuging_mode Then _FileWriteFromArray("par_file_output.parameter", $par_file_lines, 1)
   ;;;;;;;;;; RUNING THE SIMULATION ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
   If $do_cst_simulation Then
   Tray_Messages_Push('•  Simulating... .cst')
   $cst_design_environment_file = "C:\Program Files (x86)\CST STUDIO SUITE 2019\CST DESIGN ENVIRONMENT.exe"
   ;;;;;;;; chech if CST is installed or not ;;;;;;;;;;;;;;;;;;;;;;;;
	   If Not FileExists( $cst_design_environment_file ) Then
		   MsgBox(262160, "[CST Run] " & $cst_project_file_name, "The CST Design Environment executable file was not found on the defined path. @error: " & @error & @CRLF & $cst_design_environment_file, 20) ; An error occurred reading the current script file.
		   ContinueLoop
	   EndIf
   ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
		 If $debuging_mode Then MsgBox(262176, "[CST Run] " & $cst_project_file_name, '"' & $cst_design_environment_file & '"' & ' -s -se ' & '"' & $inputcstfile  & '"' , 10)
   ;;MUST BE CHANGED LIKE THIS:
   ;;"C:\Program Files (x86)\CST STUDIO SUITE 2019\CST DESIGN ENVIRONMENT.exe" -s -se -par "C:\Users\HassanPour\Desktop\New folder\parameters.par" "C:\Users\HassanPour\Desktop\New folder\Model.ems"
	  If Not $detect_and_resolve_license_release Then RunWait('"' & $cst_design_environment_file & '"' & ' -s -se ' & '"' & $inputcstfile  & '"' , "", @SW_MAXIMIZE)
	  If $detect_and_resolve_license_release Then
		 ;Global $cst_design_environment_run_PID
		 $cst_design_environment_run_PID = Run('"' & $cst_design_environment_file & '"' & ' -s -se ' & '"' & $inputcstfile  & '"' , "", @SW_MAXIMIZE)
		 If $debuging_mode Then MsgBox(0,'$cst_design_environment_run_PID', $cst_design_environment_run_PID)
		 While ProcessExists($cst_design_environment_run_PID) > 0
			If WinExists("Frontend License Released", "") Then
			   WinActivate("Frontend License Released", "")
			   Send('{ENTER}')
			EndIf
		 Sleep(30000)
		 WEnd
	  EndIf
   EndIf
   ;;;;;;;;;; READ FROM THE FILE Capacitance Matrix (lumped).stx ;;;;;;;;;;;;;;;;;;;;
   Global $capacitance_file_lines
   Tray_Messages_Push('•  Reading capacitance Matrix (.stx)')
	   If Not _FileReadToArray($cstfolder & '\Result\Capacitance Matrix (lumped).stx', $capacitance_file_lines) Then
		   MsgBox(262160, "[stx] " & $cst_project_file_name, "There was an error reading the Capacitance Matrix (.stx) file. @error: " & @error , 20) ; An error occurred reading the current script file.
		   ContinueLoop
	   EndIf
   For $i = $capacitance_file_lines[0] To 1 Step -1
   $capacitance_file_lines[$i] = StringReplace($capacitance_file_lines[$i], " F ", " ")
   $capacitance_file_lines[$i] = StringStripWS($capacitance_file_lines[$i], $STR_STRIPLEADING + $STR_STRIPTRAILING + $STR_STRIPSPACES)
   $capacitance_file_lines[$i] = StringReplace($capacitance_file_lines[$i], " ", @TAB)
	   If StringInStr(StringLeft($capacitance_file_lines[$i], 8), '-------') Then
		  _ArrayDelete($capacitance_file_lines, $i)
		ElseIf StringInStr(StringRight($capacitance_file_lines[$i], 10), '(lumped):') Then
		   _ArrayDelete($capacitance_file_lines, $i)
		ElseIf StringInStr(StringRight($capacitance_file_lines[$i], 9), '(lumped)') Then
		   _ArrayDelete($capacitance_file_lines, $i)
		ElseIf StringInStr(StringLeft($capacitance_file_lines[$i], 21), 'v_container' & @TAB & 'v_hf_down') Then
		   $capacitance_file_lines[$i] = _StringInsert($capacitance_file_lines[$i], "____" & @TAB, 0)
		ElseIf $capacitance_file_lines[$i] = "" Then
		   _ArrayDelete($capacitance_file_lines, $i)
	   EndIf
	Next
	;;;;;;;;;;;; WRITE TO THE OUTPUT (.capacitance) FILES ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
		If Not _FileWriteFromArray($capacitance_output_file, $capacitance_file_lines, 1) Then
		   MsgBox(262160, "[.capacitance] " & $cst_project_file_name, "There was an error writing the Capacitance Output (.capacitance) file. @error: " & @error , 20) ; An error occurred reading the current script file.
		   ContinueLoop
		EndIf

   ;;;;;;;;;; OPEN THE CAPACITANCE OUTPUT (.capacitance) FILE ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	   ; Open the file for reading and store the handle to a variable.
	   Local $hFileOpen = FileOpen($capacitance_output_file, $FO_READ)
	   If $hFileOpen = -1 Then
		   MsgBox(262160, "[.capacitance] " & $cst_project_file_name, "An error occurred when reading the Capacitance Output (.capacitance) file.",20)
		   ContinueLoop
	   EndIf
	   ; Read the contents of the file using the handle returned by FileOpen.
	   Global $capacitance_file_lines = FileRead($hFileOpen)
	   ; Close the handle returned by FileOpen.
	   FileClose($hFileOpen)
	   If Not $debuging_mode Then FileDelete($capacitance_output_file)

   ;;;;;;;;;; CONVERT THE CAPACITANCE OUTPUT (.capacitance) OPENED FILE TO ARRAY ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
   Local $capacitance_array = Build_Capacitance_Array($capacitance_file_lines, $column_n*2 + 7)
		  If $debuging_mode Then
		  MsgBox(262176, "[cap_array] [8][8]", $capacitance_array[8][8],10)
		  EndIf
   If $debuging_mode Then
   _ArrayDisplay($capacitance_array,'capacitance array')
   EndIf
EndIf
;;;;;;;;;;;;;;;;;;;;;;;; $column_n playes an important rule here ;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;; Extract needed values ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;; READ C_se_up ;;;;;
Global $C_se_up[100] ; !!!!!!!!!!!! THE MAXIMUM SUSTAINABLE NUMBER OF STAGES !!!!!!!!!!!!!!!
Global $C_se_down[100] ; !!!!!!!!!!!! THE MAXIMUM SUSTAINABLE NUMBER OF STAGES !!!!!!!!!!!!!!!
Global $C_ac_r[100] ; !!!!!!!!!!!! THE MAXIMUM SUSTAINABLE NUMBER OF STAGES !!!!!!!!!!!!!!!
Global $C_ac_l[100] ; !!!!!!!!!!!! THE MAXIMUM SUSTAINABLE NUMBER OF STAGES !!!!!!!!!!!!!!!
Global $C_cc_down[100] ; !!!!!!!!!!!! THE MAXIMUM SUSTAINABLE NUMBER OF STAGES !!!!!!!!!!!!!!!
Global $C_cc_up[100] ; !!!!!!!!!!!! THE MAXIMUM SUSTAINABLE NUMBER OF STAGES !!!!!!!!!!!!!!!

If Not $use_constant_values Then
   Local $iRow = _ArraySearch($capacitance_array, 'v_hf_up', 0, 0, 0, 1, 1, 0); First plate
   For $i = $column_n To 1 Step -1
	  If $i < 10 Then
		 Local $iColumn = _ArraySearch($capacitance_array, 'v_ring_up_0' & $i, 0, 0, 0, 1, 1, 0,True)
	  Else
		 Local $iColumn = _ArraySearch($capacitance_array, 'v_ring_up_' & $i, 0, 0, 0, 1, 1, 0,True)
	  EndIf
	  If @error Then
	   $error_encoutrance = True
	   MsgBox(262160,"[.capacitance] " & $cst_project_file_name, "The Predefined Plate Names were not found on the Capacitance Output (.capacitance) file." & @CRLF & 'v_hf_up' & " " & 'v_ring_up_' & $i ,20)
	   ExitLoop
	  EndIf

   $C_se_up[$i] = $capacitance_array[$iRow][$iColumn]
   If $bahraami_coefficient Then $C_se_up[$i] = $C_se_up[$i] * $bahraami_c_se_coef
   If $debuging_mode Then
   MsgBox(262176, "Extracted Value: C_se_up", $iRow & " , " & $iColumn & ": " & $capacitance_array[$iRow][$iColumn],1)
   EndIf
   Next
	  If $error_encoutrance Then
	  $error_encoutrance = False
	   MsgBox(262208,"Finished: " & $cst_project_file_name, "Continuing to the next file.",5 )
	   ContinueLoop
	  EndIf

   If $debuging_mode Then
   _ArrayDisplay($C_se_up, 'C_se_up')
   EndIf
   ;;;; READ C_se_down ;;;;;
   Local $iRow = _ArraySearch($capacitance_array, 'v_hf_down', 0, 0, 0, 1, 1, 0); First plate
   For $i = $column_n To 1 Step -1
	  If $i < 10 Then
		 Local $iColumn = _ArraySearch($capacitance_array, 'v_ring_down_0' & $i, 0, 0, 0, 1, 1, 0,True)
	  Else
		 Local $iColumn = _ArraySearch($capacitance_array, 'v_ring_down_' & $i, 0, 0, 0, 1, 1, 0,True)
	  EndIf
	  If @error Then
	   $error_encoutrance = True
	   MsgBox(262160,"[.capacitance] " & $cst_project_file_name, "The Predefined Plate Names were not found on the Capacitance Output (.capacitance) file." & @CRLF & 'v_hf_down' & " " & 'v_ring_down_' & $i ,20)
	   ExitLoop
	  EndIf

   $C_se_down[$i] = $capacitance_array[$iRow][$iColumn]
   If $bahraami_coefficient Then $C_se_down[$i] = $C_se_down[$i] * $bahraami_c_se_coef
   If $debuging_mode Then
   MsgBox(262176, "Extracted Value: C_se_down", $iRow & " , " & $iColumn & ": " & $capacitance_array[$iRow][$iColumn],1)
   EndIf
   Next
	  If $error_encoutrance Then
	  $error_encoutrance = False
	   MsgBox(262208,"Finished: " & $cst_project_file_name, "Continuing to the next file.",5 )
	   ContinueLoop
	  EndIf

   If $debuging_mode Then
   _ArrayDisplay($C_se_down, 'C_se_down')
   EndIf
   ;;;; READ C_ac_r ;;;;;
   For $i = $column_n To 1 Step -1
	  If $i < 10 Then
		 Local $iRow = _ArraySearch($capacitance_array, 'v_ring_up_0' & $i, 0, 0, 0, 1, 1, 0); First plate
		 Local $iColumn = _ArraySearch($capacitance_array, 'v_ring_down_0' & $i, 0, 0, 0, 1, 1, 0,True); Second plate
	  Else
		 Local $iRow = _ArraySearch($capacitance_array, 'v_ring_up_' & $i, 0, 0, 0, 1, 1, 0); First plate
		 Local $iColumn = _ArraySearch($capacitance_array, 'v_ring_down_' & $i, 0, 0, 0, 1, 1, 0,True); Second plate
	  EndIf
	  If @error Then
	   $error_encoutrance = True
	   MsgBox(262160,"[.capacitance] " & $cst_project_file_name, "The Predefined Plate Names were not found on the Capacitance Output (.capacitance) file." & @CRLF & 'v_ring_up_' & $i & " " & 'v_ring_down_' & $i ,20)
	   ExitLoop
	  EndIf

   $C_ac_r[$i] = $capacitance_array[$iRow][$iColumn]
   If $bahraami_coefficient Then $C_ac_r[$i] = $C_ac_r[$i] * $bahraami_c_ac_r_coef
   If $debuging_mode Then
   MsgBox(262176, "Extracted Value: C_ac_r", $iRow & " , " & $iColumn & ": " & $capacitance_array[$iRow][$iColumn],1)
   EndIf
   Next
	  If $error_encoutrance Then
	  $error_encoutrance = False
	   MsgBox(262208,"Finished: " & $cst_project_file_name, "Continuing to the next file.",5 )
	   ContinueLoop
	  EndIf
   If $debuging_mode Then
   _ArrayDisplay($C_ac_r, 'C_ac_r')
   EndIf



   ;;;;;;; 13970825 - added!! [
   For $i = $column_n-1 To 1 Step -1
	  If $i = 9 Then
		 Local $iRow = _ArraySearch($capacitance_array, 'v_ring_up_0' & $i, 0, 0, 0, 1, 1, 0); First plate
		 ;changed for sake of "not facing corona rings" for bahrami's RFP / Local $iColumn = _ArraySearch($capacitance_array, 'v_ring_down_0' & $i, 0, 0, 0, 1, 1, 0,True); Second plate
		 Local $iColumn = _ArraySearch($capacitance_array, 'v_ring_down_' & $i+1, 0, 0, 0, 1, 1, 0,True); Second plate
	  ElseIf $i < 9 Then
		 Local $iRow = _ArraySearch($capacitance_array, 'v_ring_up_0' & $i, 0, 0, 0, 1, 1, 0); First plate
		 ;changed for sake of "not facing corona rings" for bahrami's RFP / Local $iColumn = _ArraySearch($capacitance_array, 'v_ring_down_0' & $i, 0, 0, 0, 1, 1, 0,True); Second plate
		 Local $iColumn = _ArraySearch($capacitance_array, 'v_ring_down_0' & $i+1, 0, 0, 0, 1, 1, 0,True); Second plate
	  Else
		 Local $iRow = _ArraySearch($capacitance_array, 'v_ring_up_' & $i, 0, 0, 0, 1, 1, 0); First plate
		 ;changed for sake of "not facing corona rings" for bahrami's RFP / Local $iColumn = _ArraySearch($capacitance_array, 'v_ring_down_' & $i, 0, 0, 0, 1, 1, 0,True); Second plate
		 Local $iColumn = _ArraySearch($capacitance_array, 'v_ring_down_' & $i+1, 0, 0, 0, 1, 1, 0,True); Second plate
	  EndIf
	  If @error Then
	   $error_encoutrance = True
	   MsgBox(262160,"[.capacitance] ", "The Predefined Plate Names were not found on the Capacitance Output (.capacitance) file." & @CRLF & 'v_ring_up_' & $i-1 & " " & 'v_ring_down_' & $i ,20)
	   ExitLoop
	  EndIf

   $C_ac_l[$i] = $capacitance_array[$iRow][$iColumn]
   If $bahraami_coefficient Then $C_ac_l[$i] = $C_ac_l[$i] * $bahraami_c_ac_l_coef
   If $debuging_mode Then
   MsgBox(262176, "Extracted Value: C_ac_l", $iRow & " , " & $iColumn & ": " & $capacitance_array[$iRow][$iColumn],1)
   EndIf
   Next
	  If $error_encoutrance Then
	  $error_encoutrance = False
	   MsgBox(262208,"Finished: " & $cst_project_file_name, "Continuing to the next file.",5 )
	   ContinueLoop
	  EndIf
   If $debuging_mode Then
   _ArrayDisplay($C_ac_l, 'C_ac_l')
   EndIf
   ;;;;;;; 13970825 - added!! ]


   ;;;; READ C_cc_down ;;;;;
   For $i = $column_n-1 To 1 Step -1
	  If $i < 9 Then
		 Local $iRow = _ArraySearch($capacitance_array, 'v_ring_down_0' & $i, 0, 0, 0, 1, 1, 0); First plate
		 Local $iColumn = _ArraySearch($capacitance_array, 'v_ring_down_0' & $i+1, 0, 0, 0, 1, 1, 0,True); Second plate
   If $debuging_mode Then
   MsgBox(262176, "Reading: C_cc_down", $i+1, 1)
   EndIf
	  ElseIf $i = 9 Then
		 Local $iRow = _ArraySearch($capacitance_array, 'v_ring_down_0' & $i, 0, 0, 0, 1, 1, 0); First plate
		 Local $iColumn = _ArraySearch($capacitance_array, 'v_ring_down_' & $i+1, 0, 0, 0, 1, 1, 0,True); Second plate
	  Else
		 Local $iRow = _ArraySearch($capacitance_array, 'v_ring_down_' & $i, 0, 0, 0, 1, 1, 0); First plate
		 Local $iColumn = _ArraySearch($capacitance_array, 'v_ring_down_' & $i+1, 0, 0, 0, 1, 1, 0,True); Second plate
   If $debuging_mode Then
   MsgBox(262176,"Reading: C_cc_down", $i+1, 1)
   EndIf
   EndIf
	  If @error Then
	   $error_encoutrance = True
	   MsgBox(262160,"[.capacitance] " & $cst_project_file_name, "The Predefined Plate Names were not found on the Capacitance Output (.capacitance) file." & @CRLF & 'v_ring_down_' & $i & " " & 'v_ring_down_' & $i+1 ,20)
	   ExitLoop
	  EndIf

   $C_cc_down[$i] = $capacitance_array[$iRow][$iColumn]
   If $bahraami_coefficient Then $C_cc_down[$i] = $C_cc_down[$i] * $bahraami_c_cc_coef
   If $debuging_mode Then
   MsgBox(262176, "Extracted Value: C_cc_down", $iRow & "," & $iColumn & ": " & $C_cc_down[$i] , 1)
   ;MsgBox($MB_SYSTEMMODAL, "TEST", $iRow & " , " & $iColumn & ": " & $capacitance_array[$iRow][$iColumn])
   EndIf
   Next
	  If $error_encoutrance Then
	  $error_encoutrance = False
	   MsgBox(262208,"Finished: " & $cst_project_file_name, "Continuing to the next file.",5 )
	   ContinueLoop
	  EndIf

   If $debuging_mode Then
   _ArrayDisplay($C_cc_down, 'C_cc_down')
   EndIf

   ;;;; READ C_cc_up ;;;;;
   For $i = $column_n-1 To 1 Step -1
	  If $i < 9 Then
		 Local $iRow = _ArraySearch($capacitance_array, 'v_ring_up_0' & $i, 0, 0, 0, 1, 1, 0); First plate
		 Local $iColumn = _ArraySearch($capacitance_array, 'v_ring_up_0' & $i+1, 0, 0, 0, 1, 1, 0,True); Second plate
   If $debuging_mode Then
   MsgBox(262176, "Reading: C_cc_up", $i+1 , 1)
   EndIf
	  ElseIf $i = 9 Then
		 Local $iRow = _ArraySearch($capacitance_array, 'v_ring_up_0' & $i, 0, 0, 0, 1, 1, 0); First plate
		 Local $iColumn = _ArraySearch($capacitance_array, 'v_ring_up_' & $i+1, 0, 0, 0, 1, 1, 0,True); Second plate
	  Else
		 Local $iRow = _ArraySearch($capacitance_array, 'v_ring_up_' & $i, 0, 0, 0, 1, 1, 0); First plate
		 Local $iColumn = _ArraySearch($capacitance_array, 'v_ring_up_' & $i+1, 0, 0, 0, 1, 1, 0,True); Second plate
   If $debuging_mode Then
   MsgBox(262176,"Reading: C_cc_up", $i+1 , 1)
   EndIf
   EndIf
	  If @error Then
	   $error_encoutrance = True
	   MsgBox(262160,"[.capacitance] " & $cst_project_file_name, "The Predefined Plate Names were not found on the Capacitance Output (.capacitance) file." & @CRLF & 'v_ring_up_' & $i & " " & 'v_ring_up_' & $i+1 ,20)
	   ExitLoop
	  EndIf

   $C_cc_up[$i] = $capacitance_array[$iRow][$iColumn]
   If $bahraami_coefficient Then $C_cc_up[$i] = $C_cc_up[$i] * $bahraami_c_cc_coef
   If $debuging_mode Then
   MsgBox(262176, "Extracted Value: C_cc_up", $iRow & "," & $iColumn & ": " & $C_cc_up[$i] , 1)
   ;MsgBox($MB_SYSTEMMODAL, "TEST", $iRow & " , " & $iColumn & ": " & $capacitance_array[$iRow][$iColumn],10)
   EndIf
   Next
	  If $error_encoutrance Then
	  $error_encoutrance = False
	   MsgBox(262208,"Finished: " & $cst_project_file_name, "Continuing to the next file.",5 )
	   ContinueLoop
	  EndIf

   If $debuging_mode Then
   _ArrayDisplay($C_cc_up, 'C_cc_up')
   EndIf

   ;;;; READING C_f_down
   Local $iRow = _ArraySearch($capacitance_array, 'v_hf_down', 0, 0, 0, 1, 1, 0); First plate
   Local $iColumn = _ArraySearch($capacitance_array, 'v_container', 0, 0, 0, 1, 1, 0,True)
	  If @error Then
   ;    $error_encoutrance = True																; deleted because C_f_down and C_f_up are not in a "For" loop
	  MsgBox(262160,"[.capacitance] " & $cst_project_file_name, "The Predefined Plate Names were not found on the Capacitance Output (.capacitance) file." & @CRLF & 'v_hf_down' & " " & 'v_container' ,20)
	  MsgBox(262208,"Finished: " & $cst_project_file_name, "Continuing to the next file.",5 )			; copied from If error_encountrance
	   ContinueLoop																			; changed because C_f_down and C_f_up are not in a "For" loop; original: ExitLoop
	  EndIf

   $C_f_down = $capacitance_array[$iRow][$iColumn]
   If $bahraami_coefficient Then $C_f_down = $C_f_down * $bahraami_c_f_coef
   If $debuging_mode Then
   MsgBox(262176, "Extracted Value: C_f_down", $iRow & " , " & $iColumn & ": " & $capacitance_array[$iRow][$iColumn],1)
   EndIf
   ;   If $error_encoutrance Then																; deleted because C_f_down and C_f_up are not in a "For" loop
   ;   $error_encoutrance = False																; deleted because C_f_down and C_f_up are not in a "For" loop
   ;    MsgBox(262208,"" & $cst_project_file_name, "Continuing to the next file.",5 )			; deleted because C_f_down and C_f_up are not in a "For" loop
   ;	ContinueLoop																			; deleted because C_f_down and C_f_up are not in a "For" loop
   ;   EndIf																					; deleted because C_f_down and C_f_up are not in a "For" loop

   ;;;; READING C_f_up
   Local $iRow = _ArraySearch($capacitance_array, 'v_hf_up', 0, 0, 0, 1, 1, 0); First plate
   Local $iColumn = _ArraySearch($capacitance_array, 'v_container', 0, 0, 0, 1, 1, 0,True)
	  If @error Then
   ;    $error_encoutrance = True						; deleted because C_f_down and C_f_up are not in a "For" loop
	  MsgBox(262160,"[.capacitance] " & $cst_project_file_name, "The Predefined Plate Names were not found on the Capacitance Output (.capacitance) file." & @CRLF & 'v_hf_up' & " " & 'v_container' ,20)
	  MsgBox(262208,"Finished: " & $cst_project_file_name, "Continuing to the next file.",5 )			; copied from If error_encountrance
	   ContinueLoop									; changed because C_f_down and C_f_up are not in a "For" loop; original: ExitLoop
	  EndIf

   $C_f_up = $capacitance_array[$iRow][$iColumn]
   If $bahraami_coefficient Then $C_f_up = $C_f_up * $bahraami_c_f_coef
   If $debuging_mode Then
   MsgBox(262176, "Extracted Value: C_f_up", $iRow & " , " & $iColumn & ": " & $capacitance_array[$iRow][$iColumn],1)
   EndIf
   ;   If $error_encoutrance Then																; deleted because C_f_down and C_f_up are not in a "For" loop
   ;   $error_encoutrance = False																; deleted because C_f_down and C_f_up are not in a "For" loop
   ;    MsgBox(262208,"" & $cst_project_file_name, "Continuing to the next file.",5 )			; deleted because C_f_down and C_f_up are not in a "For" loop
   ;	ContinueLoop																			; deleted because C_f_down and C_f_up are not in a "For" loop
   ;   EndIf																					; deleted because C_f_down and C_f_up are not in a "For" loop


   ;;;; READING C_terminal_container
   Local $iRow = _ArraySearch($capacitance_array, 'v_hv_terminal', 0, 0, 0, 1, 1, 0); First plate
   Local $iColumn = _ArraySearch($capacitance_array, 'v_container', 0, 0, 0, 1, 1, 0,True)
	  If @error Then
   ;    $error_encoutrance = True						; deleted because C_terminal_container is not in a "For" loop
	  MsgBox(262160,"[.capacitance] " & $cst_project_file_name, "The Predefined Plate Names were not found on the Capacitance Output (.capacitance) file." & @CRLF & 'v_hv_terminal' & " " & 'v_container' ,20)
	  MsgBox(262208,"Finished: " & $cst_project_file_name, "Continuing to the next file.",5 )			; copied from If error_encountrance
	   ContinueLoop									; changed because C_terminal_container is not in a "For" loop; original: ExitLoop
	  EndIf

   $C_terminal_container = $capacitance_array[$iRow][$iColumn]
   If $bahraami_coefficient Then $C_terminal_container = $C_terminal_container * $bahraami_c_terminal_container_coef
   If $debuging_mode Then
   MsgBox(262176, "Extracted Value: C_terminal_container", $iRow & " , " & $iColumn & ": " & $capacitance_array[$iRow][$iColumn],1)
   EndIf
   ;   If $error_encoutrance Then																; deleted because C_terminal_container is not in a "For" loop
   ;   $error_encoutrance = False																; deleted because C_terminal_container is not in a "For" loop
   ;    MsgBox(262208,"" & $cst_project_file_name, "Continuing to the next file.",5 )			; deleted because C_terminal_container is not in a "For" loop
   ;	ContinueLoop																			; deleted because C_terminal_container is not in a "For" loop
   ;   EndIf																					; deleted because C_terminal_container is not in a "For" loop


   ;;;; READING C_crona_terminal_r
   Local $iRow = _ArraySearch($capacitance_array, 'v_hv_terminal', 0, 0, 0, 1, 1, 0); First plate
If $column_n < 10 Then
   Local $iColumn = _ArraySearch($capacitance_array, 'v_ring_down_0' & $column_n, 0, 0, 0, 1, 1, 0,True)
Else
   Local $iColumn = _ArraySearch($capacitance_array, 'v_ring_down_' & $column_n, 0, 0, 0, 1, 1, 0,True)
EndIf
	  If @error Then
   ;    $error_encoutrance = True																; deleted because C_crona_terminal_r is not in a "For" loop
	  MsgBox(262160,"[.capacitance] " & $cst_project_file_name, "The Predefined Plate Names were not found on the Capacitance Output (.capacitance) file." & @CRLF & 'v_hv_terminal' & " " & 'v_ring_down' ,20)
	  MsgBox(262208,"Finished: " & $cst_project_file_name, "Continuing to the next file.",5 )			; copied from If error_encountrance
	   ContinueLoop																			; changed because C_crona_terminal_r is not in a "For" loop; original: ExitLoop
	  EndIf

   $C_crona_terminal_r = $capacitance_array[$iRow][$iColumn]
   If $bahraami_coefficient Then $C_crona_terminal_r = $C_crona_terminal_r * $bahraami_c_crona_terminal_coef
   If $debuging_mode Then
   MsgBox(262176, "Extracted Value: C_crona_terminal_r", $iRow & " , " & $iColumn & ": " & $capacitance_array[$iRow][$iColumn],1)
   EndIf
   ;   If $error_encoutrance Then																; deleted because C_crona_terminal_r is not in a "For" loop
   ;   $error_encoutrance = False																; deleted because C_crona_terminal_r is not in a "For" loop
   ;    MsgBox(262208,"" & $cst_project_file_name, "Continuing to the next file.",5 )			; deleted because C_crona_terminal_r is not in a "For" loop
   ;	ContinueLoop																			; deleted because C_crona_terminal_r is not in a "For" loop
   ;   EndIf																					; deleted because C_crona_terminal_r is not in a "For" loop

   ;;;; READING C_crona_terminal_l
   Local $iRow = _ArraySearch($capacitance_array, 'v_hv_terminal', 0, 0, 0, 1, 1, 0); First plate
If $column_n < 10 Then
   Local $iColumn = _ArraySearch($capacitance_array, 'v_ring_up_0' & $column_n, 0, 0, 0, 1, 1, 0,True)
Else
   Local $iColumn = _ArraySearch($capacitance_array, 'v_ring_up_' & $column_n, 0, 0, 0, 1, 1, 0,True)
EndIf
	  If @error Then
   ;    $error_encoutrance = True						; deleted because C_crona_terminal_l is not in a "For" loop
	  MsgBox(262160,"[.capacitance] " & $cst_project_file_name, "The Predefined Plate Names were not found on the Capacitance Output (.capacitance) file." & @CRLF & 'v_hv_terminal' & " " & 'ring_up' ,20)
	  MsgBox(262208,"Finished: " & $cst_project_file_name, "Continuing to the next file.",5 )			; copied from If error_encountrance
	   ContinueLoop									; changed because C_crona_terminal_l is not in a "For" loop; original: ExitLoop
	  EndIf

   $C_crona_terminal_l = $capacitance_array[$iRow][$iColumn]
   If $bahraami_coefficient Then $C_crona_terminal_l = $C_crona_terminal_l * $bahraami_c_crona_terminal_coef
   If $debuging_mode Then
   MsgBox(262176, "Extracted Value: C_crona_terminal_l", $iRow & " , " & $iColumn & ": " & $capacitance_array[$iRow][$iColumn],1)
   EndIf
   ;   If $error_encoutrance Then																; deleted because C_crona_terminal_l is not in a "For" loop
   ;   $error_encoutrance = False																; deleted because C_crona_terminal_l is not in a "For" loop
   ;    MsgBox(262208,"" & $cst_project_file_name, "Continuing to the next file.",5 )			; deleted because C_crona_terminal_l is not in a "For" loop
   ;	ContinueLoop																			; deleted because C_crona_terminal_l is not in a "For" loop
   ;   EndIf																					; deleted because C_crona_terminal_l is not in a "For" loop
EndIf

;;;;;;;;;;;;;;; DRAW THE CIRCUIT IN THE LTSpice AND RUN ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;; DEFINING C_ac_l ;;;;;;;
; !!!!!!!!!!!!!! این مقدار باید فقط برابر ظرفیت خازنی درونی دیود قرار داده بشه یا اینکه باید از پیکربندی ستون افزاینده خونده بشه؟؟ !!!!!!!!!!!!!!;

If $use_constant_values Then
   Global $column_n = 40
   Global $C_se_value = '3.6p'
   Global $C_ac_l_value = '1.5e-12'
   Global $C_ac_r_value = '1.5e-12'
   Global $C_cc_value = '50p'
   $C_terminal_container = '100p'
   $C_f_up = '800p'
   $C_f_down = '800p'
   $C_crona_terminal_l = '50p'
   $C_crona_terminal_r = '50p'

   For $i = 0 To $column_n
			$C_se_up[$i]= $C_se_value
			$C_se_down[$i]= $C_se_value
   Next
   ;Local $C_ac_l[100]
   For $i = 0 To $column_n
			$C_ac_l[$i]= $C_ac_l_value
			$C_ac_r[$i]= $C_ac_r_value
   Next
   If $debuging_mode Then _ArrayDisplay($C_ac_l,'$C_ac_l')
   If $debuging_mode Then _ArrayDisplay($C_ac_r,'$C_ac_r')
   ;Local $C_cc_up[100]
   ;Local $C_cc_down[100]
   For $i = 0 To $column_n
			$C_cc_up[$i]= $C_cc_value
			$C_cc_down[$i]= $C_cc_value
   Next
   If $debuging_mode Then _ArrayDisplay($C_cc_up,'$C_cc_up')
   If $debuging_mode Then _ArrayDisplay($C_cc_down,'$C_cc_down')

EndIf
;;;;;;;;;;;;;; END OF TEST DATA ;;;;;;;;;;;;

Tray_Messages_Push('•  Creating and Running LTSpice File')

$starting_point_x = 480
$starting_point_y = 16
$x_step = 192
$y_step = 480
$cap_lenght = 64
$min_step_lenght = 16
$ltspice_exe_location = "C:\Program Files\LTC\LTspiceXVII\XVIIx64.exe"
;;;;;;;; check if LTSpice is installed or not ;;;;;;;;;;;;;;;;;;;;;;;;
    If Not FileExists( $ltspice_exe_location ) Then
        MsgBox(262160, "[LTSpice] " & $cst_project_file_name, "The LTSpice executable file was not found on the defined path. @error: " & @error & @CRLF & $ltspice_exe_location, 20) ; An error occurred reading the current script file.
		ContinueLoop
    EndIf
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;$column_n = 5
$RF_frequency = '100k' ; (Hz)
$Diode_intrinsic_capacitance = '3e-12'; (F)
$RF_voltage_amplitude = '50k' ;(V)
$LOAD_resistance = '10000k'
$res_lenght = 80
$start_time = '5.99m'
   If $use_constant_values Then $start_time = '0'
$max_time = '6m'
$time_step = '1m'
$LTSpice_input_asc_file_name = 'out'
$LTSpice_input_asc_file_path = @ScriptDir & '\' & $LTSpice_input_asc_file_name & '.asc'

If $debuging_mode Then
	   MsgBox(262176, "[LTSpice] output file:", $LTSpice_input_asc_file_path , 2)
EndIf


FileDelete($LTSpice_input_asc_file_path)
$working_point_x = $starting_point_x
$working_point_y = $starting_point_y + $y_step/2; - 80/2
If Not FileWriteLine($LTSpice_input_asc_file_path, "Version 4") Then
	   MsgBox(262160, "[LTSpice] " & $cst_project_file_name, "An error occurred whilst writing the LTSPice project file (.asc).",20)
       ContinueLoop
EndIf
FileWriteLine($LTSpice_input_asc_file_path, "SHEET 1 880 680")
FileWriteLine($LTSpice_input_asc_file_path, "SYMBOL voltage 0 " & $working_point_y & " R0")
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR InstName V_in_RF")

;			If $AC_analysis Then
			FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR Value AC 10")
;			Else
			FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR Value2 SINE(0 " & $RF_voltage_amplitude & " " & $RF_frequency & ")")
;			EndIf

$working_point_y = $starting_point_y

FileWriteLine($LTSpice_input_asc_file_path, "WIRE 0 "  & $starting_point_y - $cap_lenght/2 & " 0 " & $starting_point_y + $y_step + $cap_lenght/2 )




		 If $draw_center_trapped_transformer Then
FileWriteLine($LTSpice_input_asc_file_path, "WIRE " & $working_point_x - $x_step + $min_step_lenght & " " & $working_point_y + $y_step/2 - $min_step_lenght & " " & $working_point_x - $x_step + $min_step_lenght & " " & 272 )
		 Else
FileWriteLine($LTSpice_input_asc_file_path, "WIRE " & $working_point_x - $x_step + $min_step_lenght & " " & $working_point_y + $y_step/2 - $min_step_lenght & " " & $working_point_x - $x_step + $min_step_lenght & " " & $starting_point_y + $y_step + $cap_lenght/2 )
		 EndIf




For $i = $column_n To 1 Step -1
If $debuging_mode Then
	MsgBox(262176, "[LTSpice] The Stage of the Circuit Drawer", $i , 2)
EndIf
$working_point_y = $starting_point_y
; سيم‌هاي خازن‌هاي بالا: to eliminate connection to C_ac just remove  "+ $y_step/6" from the end
FileWriteLine($LTSpice_input_asc_file_path, "WIRE " & $working_point_x + $min_step_lenght & " " & $working_point_y - $min_step_lenght & " " & $working_point_x + $min_step_lenght & " " & $working_point_y + $y_step/2 - $min_step_lenght + $y_step/6)
FileWriteLine($LTSpice_input_asc_file_path, "WIRE " & $working_point_x + $min_step_lenght & " " & $working_point_y + $y_step/2 - $min_step_lenght & " " & $working_point_x + $min_step_lenght & " " & $working_point_y + $y_step/2 - $min_step_lenght + $y_step/6)
; خازن‌هاي بالا:
FileWriteLine($LTSpice_input_asc_file_path, "SYMBOL cap " & $working_point_x & " " & $working_point_y - $cap_lenght/2 & " R0")
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR InstName C_se_up_"& $column_n - $i + 1)
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR Value "& $C_se_up[$column_n - $i + 1])
    If $i <> $column_n Then
; خازن‌هاي cc پايين
FileWriteLine($LTSpice_input_asc_file_path, "SYMBOL cap " & $working_point_x - $cap_lenght/2 + $min_step_lenght & " " & $working_point_y + $y_step*(5/6) & " R270")
FileWriteLine($LTSpice_input_asc_file_path, "WINDOW 0 0 32 VBottom 2")
FileWriteLine($LTSpice_input_asc_file_path, "WINDOW 3 32 32 VTop 2")
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR InstName C_cc_down_"& $column_n - $i)
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR Value "& $C_cc_down[$column_n - $i])
    EndIf

$working_point_x = $working_point_x - $x_step/2
$working_point_y = $working_point_y + $y_step/2
; ديودهاي بالا (چپ):
FileWriteLine($LTSpice_input_asc_file_path, "SYMBOL diode " & $working_point_x & " " & $working_point_y & " R270")
FileWriteLine($LTSpice_input_asc_file_path, "WINDOW 0 32 32 VTop 2")
FileWriteLine($LTSpice_input_asc_file_path, "WINDOW 3 0 32 VBottom 2")
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR InstName D_l_" & $column_n - $i)
;FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR SpiceModel .model Cjo=" & $Diode_intrinsic_capacitance)

; سيم‌هاي خازن‌هاي پايين:
FileWriteLine($LTSpice_input_asc_file_path, "WIRE " & $working_point_x + $x_step + $x_step/2 + $min_step_lenght & " " & $working_point_y - $min_step_lenght & " " & $working_point_x + $x_step + $x_step/2 + $min_step_lenght & " " & $starting_point_y + $y_step + $cap_lenght/2 )

; خازن‌هاي C_ac موازي با ديود (چپ):
FileWriteLine($LTSpice_input_asc_file_path, "SYMBOL cap " & $working_point_x & " " & $working_point_y + $y_step/6 & " R270")
FileWriteLine($LTSpice_input_asc_file_path, "WINDOW 0 0 32 VBottom 2")
FileWriteLine($LTSpice_input_asc_file_path, "WINDOW 3 32 32 VTop 2")
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR InstName C_ac_l_"& $column_n - $i)
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR Value "& $C_ac_l[$column_n - $i]+$Diode_intrinsic_capacitance)
; سيم خازن‌هاي ac
FileWriteLine($LTSpice_input_asc_file_path, "WIRE "& $working_point_x - $x_step/2 + $min_step_lenght & " " & $starting_point_y + $y_step/2 - $min_step_lenght + $y_step/6 & " " & $working_point_x + $x_step + $x_step/2 + $min_step_lenght& " " & $starting_point_y + $y_step/2 - $min_step_lenght + $y_step/6)

    If $i <> $column_n Then
; سيم‌هاي خازن‌هاي cc پايين
FileWriteLine($LTSpice_input_asc_file_path, "WIRE "& $working_point_x - $x_step/2 + $min_step_lenght  & " " & $starting_point_y + $y_step*(5/6) - $min_step_lenght & " " & $working_point_x + $x_step + $x_step/2 + $min_step_lenght& " " & $starting_point_y + $y_step*(5/6) - $min_step_lenght)
    EndIf
$working_point_x = $working_point_x + $x_step
; ديودهاي پايين (راست)
FileWriteLine($LTSpice_input_asc_file_path, "SYMBOL diode " & $working_point_x & " " & $working_point_y & " R270")
FileWriteLine($LTSpice_input_asc_file_path, "WINDOW 0 32 32 VTop 2")
FileWriteLine($LTSpice_input_asc_file_path, "WINDOW 3 0 32 VBottom 2")
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR InstName D_r_" & $column_n - $i)
;FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR SpiceModel .model Cjo=" & $Diode_intrinsic_capacitance)

; خازن‌هاي C_ac موازي با ديود (راست):
FileWriteLine($LTSpice_input_asc_file_path, "SYMBOL cap " & $working_point_x & " " & $working_point_y + $y_step/6 & " R270")
FileWriteLine($LTSpice_input_asc_file_path, "WINDOW 0 0 32 VBottom 2")
FileWriteLine($LTSpice_input_asc_file_path, "WINDOW 3 32 32 VTop 2")
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR InstName C_ac_r_"& $column_n - $i)
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR Value "& $C_ac_r[$column_n - $i + 1]+$Diode_intrinsic_capacitance)

$working_point_x = $working_point_x + $x_step/2
$working_point_y = $working_point_y + $y_step/2
; خازن‌هاي پايين
FileWriteLine($LTSpice_input_asc_file_path, "SYMBOL cap " & $working_point_x & " " & $working_point_y - $cap_lenght/2 & " R0")
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR InstName C_se_down_"& $column_n - $i + 1)
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR Value "& $C_se_down[$column_n - $i + 1])

    If $i <> $column_n Then
; خازن‌هاي cc بالا
FileWriteLine($LTSpice_input_asc_file_path, "SYMBOL cap " & $working_point_x - 2*$x_step - $cap_lenght/2 + $min_step_lenght & " " & $starting_point_y + $y_step*(1/6) & " R270")
FileWriteLine($LTSpice_input_asc_file_path, "WINDOW 0 0 32 VBottom 2")
FileWriteLine($LTSpice_input_asc_file_path, "WINDOW 3 32 32 VTop 2")
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR InstName C_cc_up_"& $column_n - $i)
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR Value "& $C_cc_up[$column_n - $i])
    EndIf
; سيم‌هاي خازن‌هاي cc بالا
    If $i <> 0 Then
FileWriteLine($LTSpice_input_asc_file_path, "WIRE "& $working_point_x - $x_step + $min_step_lenght & " " & $starting_point_y + $y_step*(1/6) - $min_step_lenght & " " & $working_point_x + $x_step + $min_step_lenght& " " & $starting_point_y + $y_step*(1/6) - $min_step_lenght)
    EndIf
$working_point_x = $working_point_x + $x_step
Next


If $draw_center_trapped_transformer Then
FileWriteLine($LTSpice_input_asc_file_path, "WIRE 0 "& $starting_point_y - $cap_lenght/2 & " " & 128 & " " & $starting_point_y - $cap_lenght/2 )
FileWriteLine($LTSpice_input_asc_file_path, "WIRE 208 "& $starting_point_y - $cap_lenght/2 & " " & $working_point_x - $x_step*2 + $min_step_lenght & " " & $starting_point_y - $cap_lenght/2 )
Else
; سيم آر اف بالايي:
FileWriteLine($LTSpice_input_asc_file_path, "WIRE 0 "& $starting_point_y - $cap_lenght/2 & " " & $working_point_x - $x_step*2 + $min_step_lenght & " " & $starting_point_y - $cap_lenght/2 )
EndIf
; سيم ديودها (وسط):
FileWriteLine($LTSpice_input_asc_file_path, "WIRE "& $starting_point_x - $x_step + $min_step_lenght & " " & $starting_point_y + $y_step/2 - $min_step_lenght & " " & $working_point_x - $x_step + $min_step_lenght & " " & $starting_point_y + $y_step/2 - $min_step_lenght )
If $draw_center_trapped_transformer Then
FileWriteLine($LTSpice_input_asc_file_path, "WIRE 0 "& $starting_point_y + $y_step + $cap_lenght/2 & " " & 128 & " " & $starting_point_y + $y_step + $cap_lenght/2 )
FileWriteLine($LTSpice_input_asc_file_path, "WIRE 208 "& $starting_point_y + $y_step + $cap_lenght/2 & " " & $working_point_x - $x_step + $min_step_lenght & " " & $starting_point_y + $y_step + $cap_lenght/2 )
Else
; سيم آر اف پاييني:
FileWriteLine($LTSpice_input_asc_file_path, "WIRE 0 "& $starting_point_y + $y_step + $cap_lenght/2 & " " & $working_point_x - $x_step + $min_step_lenght & " " & $starting_point_y + $y_step + $cap_lenght/2 )
EndIf


; خازن C_f_down
   If $draw_both_c_f Then
FileWriteLine($LTSpice_input_asc_file_path, "SYMBOL cap " & $working_point_x/2 & " " & $starting_point_y + $y_step + $cap_lenght/2 & " R0")
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR InstName C_f_down")
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR Value "& $C_f_down)
   EndIf
FileWriteLine($LTSpice_input_asc_file_path, "FLAG " & $working_point_x/2 + $min_step_lenght & " " & $starting_point_y + $y_step + 150 & " 0" )
FileWriteLine($LTSpice_input_asc_file_path, "WIRE " & $working_point_x/2 + $min_step_lenght & " " & $starting_point_y + $y_step + $cap_lenght/2 & " " & $working_point_x/2 + $min_step_lenght & " " & $starting_point_y + $y_step + 150 )

; خازن C_f_up
FileWriteLine($LTSpice_input_asc_file_path, "SYMBOL cap " & $working_point_x/2 & " " & $starting_point_y - $cap_lenght - $cap_lenght/2 & " R0")
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR InstName C_f_up")
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR Value "& $C_f_up)
FileWriteLine($LTSpice_input_asc_file_path, "FLAG " & $working_point_x/2 + $min_step_lenght & " " & $starting_point_y - $cap_lenght - $cap_lenght/2 - 50  & " 0" )
FileWriteLine($LTSpice_input_asc_file_path, "WIRE " & $working_point_x/2 + $min_step_lenght & " " & $starting_point_y - $cap_lenght - $cap_lenght/2 & " " & $working_point_x/2 + $min_step_lenght & " " & $starting_point_y - $cap_lenght - $cap_lenght/2 - 50 )


; خازن C_terminal_container
FileWriteLine($LTSpice_input_asc_file_path, "SYMBOL cap " &  $working_point_x - $x_step/2 + $cap_lenght - $min_step_lenght & " " & $starting_point_y - $cap_lenght - $cap_lenght/2 & " R0")
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR InstName C_terminal_container")
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR Value "& $C_terminal_container)
FileWriteLine($LTSpice_input_asc_file_path, "FLAG " & $working_point_x - $x_step/2 + $cap_lenght & " " & $starting_point_y - $cap_lenght - $cap_lenght/2 - 50  & " 0" )
FileWriteLine($LTSpice_input_asc_file_path, "WIRE " & $working_point_x - $x_step/2 + $cap_lenght & " " & $starting_point_y - $cap_lenght - $cap_lenght/2 & " " & $working_point_x - $x_step/2 + $cap_lenght & " " & $starting_point_y - $cap_lenght - $cap_lenght/2 - 50 )
FileWriteLine($LTSpice_input_asc_file_path, "WIRE " & $working_point_x - $x_step/2 + $cap_lenght & " " & $starting_point_y - $cap_lenght/2 & " " & $working_point_x - $x_step/2 + $cap_lenght & " " & $starting_point_y + $y_step*(1/6) - $min_step_lenght )


; خازن C_crona_terminal بالا 	بین آخرین کرونا و گنبد	+ سیم
FileWriteLine($LTSpice_input_asc_file_path, "WIRE "& $working_point_x - $x_step - $x_step + $min_step_lenght & " " & $starting_point_y + $y_step*(1/6) - $min_step_lenght & " " & $working_point_x - $x_step/2 & " " & $starting_point_y + $y_step*(1/6) - $min_step_lenght)
FileWriteLine($LTSpice_input_asc_file_path, "SYMBOL cap " & $working_point_x - $x_step/2 & " " & $starting_point_y + $y_step*(1/6) & " R270")
FileWriteLine($LTSpice_input_asc_file_path, "WINDOW 0 0 32 VBottom 2")
FileWriteLine($LTSpice_input_asc_file_path, "WINDOW 3 32 32 VTop 2")
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR InstName C_crona_terminal_l")
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR Value "& $C_crona_terminal_l)

; خازن C_crona_terminal پایین 	بین آخرین کرونا و گنبد	+ سیم
FileWriteLine($LTSpice_input_asc_file_path, "WIRE "& $working_point_x - $x_step + $min_step_lenght & " " & $starting_point_y + $y_step*(5/6) - $min_step_lenght & " " & $working_point_x - $x_step/2 & " " & $starting_point_y + $y_step*(5/6) - $min_step_lenght)
$replace_C_crona_terminal_r_with_WIRE = True
   If $replace_C_crona_terminal_r_with_WIRE Then
FileWriteLine($LTSpice_input_asc_file_path, "WIRE "& $working_point_x - $x_step/2 & " " & $starting_point_y + $y_step*(5/6) - $min_step_lenght & " " & $working_point_x - $x_step/2 + $cap_lenght & " " & $starting_point_y + $y_step*(5/6) - $min_step_lenght)
   Else
FileWriteLine($LTSpice_input_asc_file_path, "SYMBOL cap " & $working_point_x - $x_step/2 & " " & $starting_point_y + $y_step*(5/6) & " R270")
FileWriteLine($LTSpice_input_asc_file_path, "WINDOW 0 0 32 VBottom 2")
FileWriteLine($LTSpice_input_asc_file_path, "WINDOW 3 32 32 VTop 2")
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR InstName C_crona_terminal_r")
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR Value "& $C_crona_terminal_r)
   EndIf

; سیم نماینده‌ی گنبد در مدار		terminal
FileWriteLine($LTSpice_input_asc_file_path, "WIRE "& $working_point_x - $x_step/2 + $cap_lenght & " " & $starting_point_y + $y_step*(1/6) - $min_step_lenght & " " & $working_point_x - $x_step/2 + $cap_lenght & " " & $starting_point_y + $y_step*(5/6) - $min_step_lenght)


If $draw_load_resistance Then ;;;;;;;;;;; NO NEED TO SHOW IF THERE IS NO LOAD ;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;; بار ;;;;;;;;;;;;;;  LOAD ;;;;;;;;;;;;;;;;;;;;;;;
FileWriteLine($LTSpice_input_asc_file_path, "SYMBOL res " & $working_point_x + $x_step & " " & $starting_point_y + $y_step + $min_step_lenght & " R0")
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR InstName LOAD")
FileWriteLine($LTSpice_input_asc_file_path, "SYMATTR Value " & $LOAD_resistance)
; سيم و ارت مقاومت بار
FileWriteLine($LTSpice_input_asc_file_path, "FLAG " & $working_point_x + $x_step + $min_step_lenght & " " & $starting_point_y + $y_step + 150 & " 0" )
FileWriteLine($LTSpice_input_asc_file_path, "WIRE " & $working_point_x + $x_step + $min_step_lenght & " " & $starting_point_y + $y_step + $cap_lenght/2 + $res_lenght & " " & $working_point_x + $x_step + $min_step_lenght & " " & $starting_point_y + $y_step + 150 )
FileWriteLine($LTSpice_input_asc_file_path, "WIRE " & $working_point_x + $x_step + $min_step_lenght & " " & $starting_point_y + $y_step/2 - $min_step_lenght & " " & $working_point_x + $x_step + $min_step_lenght & " " & $starting_point_y + $y_step + $cap_lenght/2 )
; سيم افقي مرتبط کننده‌ي سيم ارت و سيم نماينده‌ي گنبد
FileWriteLine($LTSpice_input_asc_file_path, "WIRE " & $working_point_x - $x_step/2 + $cap_lenght & " " & $starting_point_y + $y_step/2 - $min_step_lenght & " " & $working_point_x + $x_step + $min_step_lenght & " " & $starting_point_y + $y_step/2 - $min_step_lenght )
EndIf

		 If $draw_center_trapped_transformer Then
		 FileWriteLine($LTSpice_input_asc_file_path, "WIRE 496 -16 208 -16" & @CRLF & "WIRE 208 176 208 -16" & @CRLF & "WIRE 128 224 128 -16" & @CRLF & "WIRE 208 272 208 256" & @CRLF & "WIRE 256 272 208 272" & @CRLF & "WIRE 304 272 256 272" & @CRLF & "WIRE 208 304 208 272" & @CRLF & "WIRE 304 320 304 272" & @CRLF & "WIRE 256 384 256 272" & @CRLF & "WIRE 128 528 48 528" & @CRLF & "WIRE 208 528 208 384" & @CRLF & "WIRE 48 608 48 528" & @CRLF & "FLAG 256 384 0" & @CRLF & "FLAG 48 608 0" & @CRLF & "WIRE 128 528 128 304" )
		 FileWriteLine($LTSpice_input_asc_file_path, "SYMBOL ind2 112 208 R0" & @CRLF & "SYMATTR InstName L_primary" & @CRLF & "SYMATTR Value 0.005" & @CRLF & "SYMATTR Type ind" & @CRLF & "SYMATTR SpiceLine Rser=0.000001" & @CRLF & "SYMBOL ind2 224 272 R180" & @CRLF & "WINDOW 0 36 80 Left 2" & @CRLF & "WINDOW 3 36 40 Left 2" & @CRLF & "SYMATTR InstName L_secondary_up" & @CRLF & "SYMATTR Value 0.005" & @CRLF & "SYMATTR Type ind" & @CRLF & "SYMBOL ind2 224 400 R180" & @CRLF & "WINDOW 0 36 80 Left 2" & @CRLF & "WINDOW 3 36 40 Left 2" & @CRLF & "SYMATTR InstName L_secondary_down" & @CRLF & "SYMATTR Value 0.005" & @CRLF & "SYMATTR Type ind" & @CRLF & "TEXT 72 152 Left 2 !K1 L_primary L_secondary_up L_secondary_down 1" )

		 EndIf

;	Simulation Settings:
		 If $AC_analysis Then
		 FileWriteLine($LTSpice_input_asc_file_path, "TEXT -32 448 Left 2 !.ac lin 10000 80k 600k" )
		 Else
		 FileWriteLine($LTSpice_input_asc_file_path, "TEXT -34 444 Left 2 !.tran 0 " & $max_time & " " & $start_time & " " & $time_step )
		 EndIf
;   سیم گراند مربوط به ورژن قبلی مدار که خازن‌های C_f رو نداشتیم.
;FileWriteLine($LTSpice_input_asc_file_path, "FLAG 0 " & $starting_point_y + $y_step + 100 & " 0" )
;FileWriteLine($LTSpice_input_asc_file_path, "WIRE 0 " & $starting_point_y + $y_step & " 0 " & $starting_point_y + $y_step + 100 )

;WIRE 576 192 448 192

If $debuging_mode Then
MsgBox(262176, "[LTSpice] Running Command",'"' & $ltspice_exe_location & '"' & ' "' & $LTSpice_input_asc_file_path &  '"' , 10)
EndIf
MouseMove(0, 0, 0) ; Move the mouse cursor to the x, y position of 0, 0. To Avoid mouse confliction.
Run( '"' & $ltspice_exe_location & '"' & ' -Run "' & $LTSpice_input_asc_file_path &  '"', @WindowsDir, @SW_MAXIMIZE)

If WinWaitActive("LTspice XVII - out", "", 30) = 0 Then		; If the window did not actived after a while then chech if it is crashed
   		 If WinExists("[CLASS:Ghost]") Then					;If it is crashed then kill the process.
		 $LTSpicePID = WinGetProcess("[CLASS:Ghost]")
		 MsgBox($MB_SYSTEMMODAL, $LTSpicePID , "Seems LTSpice has been crashed",5)
		 Run ( "TASKKILL /F /IM " & "XVIIx64.exe")
		 ProcessClose($LTSpicePID)
		 WinKill ( "[CLASS:Ghost]" )
		 EndIf
EndIf

 $i=1
Do
$LTSpice_statusbar = StatusbarGetText("LTspice XVII - out" , "" , "1")
If $debuging_mode Then
MsgBox(262176, "[LTSpice] StatusBar", StatusbarGetText("LTspice XVII - out" , "" , "1"), 0.5)
EndIf
$i=$i+1
    If IsInt($i/450000) = 1 And StringLeft($LTSpice_statusbar, 15) <> StringLeft("Simulation Time = ",15) Then
		 If WinExists("[CLASS:Ghost]") Then
		 MsgBox($MB_SYSTEMMODAL, "[LTSpice] 2nd crashing trap.", "Seems LTSpice has been crashed",5)
		 WinKill ( "[CLASS:Ghost]" )
		 $error_encoutrance = True
		 ExitLoop
		 EndIf
			If MsgBox(36, "[LTSpice] Getting StatusBar Messages", "Shall I stop waiting now and export the data acomulated so far?",20) <> 7 Then
			   ExitLoop
			EndIf
    EndIf
Until StringLeft($LTSpice_statusbar, 25) = StringLeft("Processing .MEASURE commands",25) or StringLeft($LTSpice_statusbar, 23) = 'Loading Operating Point' or $i = 3000000000 ;  or StringLeft($LTSpice_statusbar, 5) = 'Ready'
    If $error_encoutrance Then
    $error_encoutrance = False
    MsgBox(262208,"[LTSpice] crashed or unknown state" & $cst_project_file_name, "Continuing to the next file.",5 )
	ContinueLoop
   EndIf
If $debuging_mode Then
   MsgBox(262176, "[LTSpice] Number of Done loops", $i , 10)
EndIf
If $draw_load_resistance Then ;;;;;;;;;;; NO NEED TO SHOW IF THERE IS NO LOAD ;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;; Exporing Current output ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
 WinActivate("LTspice XVII - out", "")
 Send ("^h") ; stop the simulation
 Send ("!W")
 Send ("2")
 Send ("!F")
 Send ("E")
 WinWaitActive("Select Traces to Export", "OK", 30)
    ControlClick("Select Traces to Export", "OK", "Edit1")
If $debuging_mode Then
			Sleep ( 1000 )
EndIf
	Send("^A")
	Send("{DEL}")
    Local $LTSpice_current_output_file = @ScriptDir & "\" & $cst_project_file_name & "." & $DateStr & ".current"
    Send ($LTSpice_current_output_file)
If $debuging_mode Then
			Sleep ( 1000 )
EndIf
    ControlClick("Select Traces to Export", "OK", "ListBox1")
	WinActivate("Select Traces to Export", "OK")
	Send ("{END}")
If $debuging_mode Then
			Sleep ( 1000 )
EndIf
	Send ("{UP}")
If $debuging_mode Then
			Sleep ( 1000 )
EndIf
Send("{ENTER}")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
EndIf
;;;;;;;;;;;;;;; Exporing Voltage output ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
 WinActivate("LTspice XVII - out", "")
 Send ("^h") ; stop the simulation
 Send ("!W")
 Send ("2")
 Send ("!F")
 Send ("E")
 WinWaitActive("Select Traces to Export", "OK", 30)
    ControlClick("Select Traces to Export", "OK", "Edit1")
If $debuging_mode Then
			Sleep ( 1000 )
EndIf
	Send("^A")
	Send("{DEL}")
    Local $LTSpice_voltage_output_file = @ScriptDir & "\" & $cst_project_file_name & "." & $DateStr & ".voltage"
    Send ($LTSpice_voltage_output_file)
If $debuging_mode Then
			Sleep ( 1000 )
EndIf
    ControlClick("Select Traces to Export", "OK", "ListBox1")
	WinActivate("Select Traces to Export", "OK")
	Send ("{HOME}")
If $debuging_mode Then
			Sleep ( 1000 )
EndIf
;   MsgBox(0, "Error",($column_n+1)*2+1,30)
For $i = ($column_n+2) To 1 Step -1
;   MsgBox(0, "Error",$i,30)
	Send ("v")
 Next

If $draw_center_trapped_transformer Then
;   	Send ("v") ; send v one more time because the nodes numbers change when we draw the transformer
;				   ; caused some problems ion the newer version!!!!
EndIf

If $debuging_mode Then
			Sleep ( 1000 )
EndIf
Send("{ENTER}")

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
   If $debuging_mode Then
   MsgBox(262208, "[LTSpice] Done!","The LTSpice simulation has been done successfully till now I hope. :)",0.5)
;   MsgBox(64, "Done!",$LTSpice_voltage_output_file,10)
   EndIf
If $close_LTSpice_at_finish Then
 WinActivate("LTspice XVII - out", "")
 Send("!{F4}")
EndIf

If $draw_load_resistance Then ;;;;;;;;;;; NO NEED TO SHOW IF THERE IS NO LOAD ;;;;;;;;;;;;;;;;;;;;;;;;
Tray_Messages_Push('•  Waiting for (.current) file readablity')
;;;;;;;;;;;;; Wait till the LTSpice Current Output file becomes readable (Not Empty) + Not changing based on last line sampling; 139607050324 ;;;;;;;;;
If $debuging_mode Then
   MsgBox(262208, "[post_processing] Looking for the Output file:",$LTSpice_current_output_file & @CRLF & "Make sure that the name is not too long and doesn't contain any special characters." ,30)
EndIf

 	Do
	  FileReadToArray($LTSpice_current_output_file)
	  If @error = 2 Then
;		MsgBox(262176, "[post_processing] " & $cst_project_file_name, "The file is still empty. @error: " & @error,10) ; An error occurred reading the current script file.
	  ElseIf @error = 1 Then
		 $error_encoutrance = True
		 MsgBox(262160, "[post_processing] " & $cst_project_file_name, "There was an error reading the Current Output (.current) file. FileReadToArray @error: " & @error & @CRLF & "Make sure that the name is not too long and doesn't contain any special characters." ,20) ; An error occurred reading the current script file.
		 ExitLoop
	  EndIf
		 $lastline_LTSpice_current_output_1 = FileReadLine($LTSpice_current_output_file,-1)
		 sleep (1000)
		 $lastline_LTSpice_current_output_2 = FileReadLine($LTSpice_current_output_file,-1)
If $debuging_mode Then
			   MsgBox(262176, "[post_processing] Last lines" & $LTSpice_current_output_file,"comparing the two sampling of last lines of the (.current) file." & $lastline_LTSpice_current_output_1 & @CRLF & $lastline_LTSpice_current_output_2 & @CRLF & @error,0.5)
EndIf
    $i=$i+1
;	sleep ( 1000 )
   If IsInt($i/1500) = 1  Then
	  If MsgBox(36, "[post_processing] Reading LTSpice Current Output file", "There seem to be an error reading the LTSpice output current (.current) file. The last line is still changing!! [under modification maybe]. Shall I stop now or wait for another 1500*100 ms?",60) <> 7 Then
		 ExitLoop
	  EndIf
   EndIf
	Until $lastline_LTSpice_current_output_1 =$lastline_LTSpice_current_output_2 and $lastline_LTSpice_current_output_1 <> ''

    If $error_encoutrance Then
    $error_encoutrance = False
    MsgBox(262208,"[post_processing] Error opening LTSpice Current output (.current) file." & $cst_project_file_name, "Continuing to the next file.",5 )
	ContinueLoop
   EndIf

If $debuging_mode Then
	  			MsgBox(262176, "[post_processing] " & $cst_project_file_name, "The last line of the LTSpice current output (.current) file is: " & FileReadLine($LTSpice_current_output_file,-1) & @CRLF & "@error: " & @error , 10)
EndIf
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
EndIf
Tray_Messages_Push('•  Waiting for (.voltage) file readablity')
;;;;;;;;;;;;; Wait till the LTSpice Voltage Output file becomes readable (Not Empty) + Not changing based on last line sampling; 139607050324 ;;;;;;;;;
If $debuging_mode Then
   MsgBox(262208, "[post_processing] Looking for the Output file:",$LTSpice_voltage_output_file & @CRLF & "Make sure that the name is not too long and doesn't contain any special characters." ,30)
EndIf

 	Do
	  FileReadToArray($LTSpice_voltage_output_file)
	  If @error = 2 Then
;		MsgBox(262176, "[post_processing] " & $cst_project_file_name, "The file is still empty. @error: " & @error,10) ; An error occurred reading the current script file.
	  ElseIf @error = 1 Then
		 $error_encoutrance = True
		 MsgBox(262160, "[post_processing] " & $cst_project_file_name, "There was an error reading the Voltage Output (.voltage) file. FileReadToArray @error: " & @error & @CRLF & "Make sure that the name is not too long and doesn't contain any special characters." ,20) ; An error occurred reading the current script file.
		 ExitLoop
	  EndIf
		 $lastline_LTSpice_voltage_output_1 = FileReadLine($LTSpice_voltage_output_file,-1)
		 sleep (1000)
		 $lastline_LTSpice_voltage_output_2 = FileReadLine($LTSpice_voltage_output_file,-1)
If $debuging_mode Then
			   MsgBox(262176, "[post_processing] Last lines" & $LTSpice_voltage_output_file,"comparing the two sampling of last lines of the (.voltage) file." & $lastline_LTSpice_voltage_output_1 & @CRLF & $lastline_LTSpice_voltage_output_2 & @CRLF & @error,0.5)
EndIf
    $i=$i+1
;	sleep ( 1000 )
   If IsInt($i/1500) = 1  Then
	  If MsgBox(36, "[post_processing] Reading LTSpice Voltage Output file", "There seem to be an error reading the LTSpice output voltage (.voltage) file. The last line is still changing!! [under modification maybe]. Shall I stop now or wait for another 1500*100 ms?",60) <> 7 Then
		 ExitLoop
	  EndIf
   EndIf
	Until $lastline_LTSpice_voltage_output_1 =$lastline_LTSpice_voltage_output_2 and $lastline_LTSpice_voltage_output_1 <> ''

    If $error_encoutrance Then
    $error_encoutrance = False
    MsgBox(262208,"[post_processing] Error opening LTSpice Voltage output (.voltage) file." & $cst_project_file_name, "Continuing to the next file.",5 )
	ContinueLoop
   EndIf

If $debuging_mode Then
	  			MsgBox(262176, "[post_processing] " & $cst_project_file_name, "The last line of the LTSpice voltage output (.voltage) file is: " & FileReadLine($LTSpice_voltage_output_file,-1) & @CRLF & "@error: " & @error , 10)
EndIf
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
$result_summary_file = @ScriptDir & "\" & $cst_project_file_name & "." & $DateStr & "_result_summary.o" ;;;;; THE OUTPUT FILE ;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

If $draw_load_resistance Then ;;;;;;;;;;; NO NEED TO SHOW IF THERE IS NO LOAD ;;;;;;;;;;;;;;;;;;;;;;;;
Tray_Messages_Push('•  Reading (.current) file')
;;;;;;;;;; OPEN THE LTSPICE CURRENT OUTPUT (.current) FILE ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ; Open the file for reading and store the handle to a variable.
    Local $LTSpice_current_output_FileOpen = FileOpen($LTSpice_current_output_file, $FO_READ)
    If $LTSpice_current_output_FileOpen = -1 Then
        MsgBox(262160, "[post_processing] " & $cst_project_file_name, "An error occurred when reading the LTSpice Current Output (.current) file.",60)
        ContinueLoop
    EndIf
    ; Read the contents of the file using the handle returned by FileOpen.
    Global $LTSpice_current_output_file_lines = FileRead($LTSpice_current_output_FileOpen)
    ; Close the handle returned by FileOpen.
    FileClose($LTSpice_current_output_FileOpen)
	If $debuging_mode Then
     If FileExists ( @ScriptDir & "\" & 'tmp.curnt') Then
	    If Not FileDelete ( @ScriptDir & "\" & 'tmp.curnt' ) Then
			MsgBox(262160, "[post_processing] " & $cst_project_file_name, "There was an error deleting the existing tmp.curnt file. @error: " & @error , 20) ; An error occurred reading the current script file.
	    EndIf
	 EndIf
    FileWrite( @ScriptDir & "\" & 'tmp.curnt' , $LTSpice_current_output_file_lines )
	EndIf
$ignorance_region_of_current_percent = 95; The region at the begining of the Current curve that will not be considered for determining ripple and mean current (%)
;$LTSpice_current_output_file_lines = '1234567890123456789012345678901234567890'
Tray_Messages_Push('•  Trimming the read (.current) file')
$LTSpice_current_output_file_lines = StringTrimLeft($LTSpice_current_output_file_lines, StringLen($LTSpice_current_output_file_lines)*$ignorance_region_of_current_percent/100) ; Remove some Leftmost characters from the string.
$LTSpice_current_output_file_lines = StringTrimRight($LTSpice_current_output_file_lines, 2) ; Remove the last line from the string.
;;;;;;;;;; CONVERT THE LTSPICE CURRENT OUTPUT (.current) OPENED FILE TO ARRAY ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Local $LTSpice_current_output_array = Build_Current_output_Array($LTSpice_current_output_file_lines, 2)
If $debuging_mode Then
_ArrayDisplay($LTSpice_current_output_array,'Current output Array')
EndIf

 ;;;;;;;;;;;;;;; READ RIPPLE AND CURRENT FROM LTSPICE ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Tray_Messages_Push('•  Calculating (.current) file ripple and mean')
         $sum = 0
	  For $i = 0 To UBound($LTSpice_current_output_array, 1)-1
;		 If $debuging_mode Then
;		   MsgBox(262176, "test array",  $LTSpice_current_output_array[$i][1],1)
;		 EndIf
		 $sum = $sum + $LTSpice_current_output_array[$i][1]
	  Next
$mean_current = $sum / UBound($LTSpice_current_output_array, 1)
$min_current = _ArrayMin($LTSpice_current_output_array, 1, -1,-1,1)
$max_current = _ArrayMax($LTSpice_current_output_array, 1, -1,-1,1)
If $debuging_mode Then
     If FileExists ( @ScriptDir & "\" & "filtered_(considered)_data_range.current" ) Then
	    If Not FileDelete ( @ScriptDir & "\" & "filtered_(considered)_data_range.current" ) Then
			MsgBox(262160, "[post_processing] " & $cst_project_file_name, "There was an error deleting the existing Considered Current Range (.current) file. @error: " & @error , 20) ; An error occurred reading the current script file.
	    EndIf
	 EndIf
	    If Not FileWrite( @ScriptDir & "\" & "filtered_(considered)_data_range.current" ,_ArrayToString($LTSpice_current_output_array)) Then
			MsgBox(262160, "[post_processing] " & $cst_project_file_name, "There was an error writing the Considered Current Range (.current) file. @error: " & @error , 20) ; An error occurred reading the current script file.
		ContinueLoop
	    EndIf

   MsgBox(262176, "[post_processing] Current: No. of DATA",  (UBound($LTSpice_current_output_array, 1)-1) , 10)
   MsgBox(262176, "[post_processing] Current: Mean Value",  $mean_current, 1 , 10)
EndIf
        If Not FileWrite($result_summary_file , 'Current (Ampere) : ' & @CRLF & 'Min: ' & $min_current & @CRLF &"Max: " & $max_current & @CRLF & "Difference: " & $max_current - $min_current & @CRLF & "Mean Value: " & $mean_current & @CRLF & @CRLF ) Then
        MsgBox(262160, "[post_processing] " & $cst_project_file_name, "There was an error writing the Result Summary (.o) file. @error: " & @error,60) ; An error occurred reading the current script file.
		ContinueLoop
	    EndIf
 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
EndIf
Tray_Messages_Push('•  Reading (.voltage) file')
;;;;;;;;;; OPEN THE LTSPICE VOLTAGE OUTPUT (.voltage) FILE ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ; Open the file for reading and store the handle to a variable.
    Local $LTSpice_voltage_output_FileOpen = FileOpen($LTSpice_voltage_output_file, $FO_READ)
    If $LTSpice_voltage_output_FileOpen = -1 Then
        MsgBox(262160, "[post_processing] " & $cst_project_file_name, "An error occurred when reading the LTSpice Voltage Output (.voltage) file.",60)
        ContinueLoop
    EndIf
    ; Read the contents of the file using the handle returned by FileOpen.
    Global $LTSpice_voltage_output_file_lines = FileRead($LTSpice_voltage_output_FileOpen)
    ; Close the handle returned by FileOpen.
    FileClose($LTSpice_voltage_output_FileOpen)
	If $debuging_mode Then
     If FileExists ( @ScriptDir & "\" & 'tmp.volt') Then
	    If Not FileDelete ( @ScriptDir & "\" & 'tmp.volt' ) Then
			MsgBox(262160, "[post_processing] " & $cst_project_file_name, "There was an error deleting the existing tmp.volt file. @error: " & @error , 20) ; An error occurred reading the current script file.
	    EndIf
	 EndIf
    FileWrite( @ScriptDir & "\" & 'tmp.volt' , $LTSpice_voltage_output_file_lines )
	EndIf
$ignorance_region_of_voltage_percent = 95; The region at the begining of the Voltage curve that will not be considered for determining ripple and mean voltage (%)
;$LTSpice_voltage_output_file_lines = '1234567890123456789012345678901234567890'
Tray_Messages_Push('•  Trimming the read (.voltage) file')
$LTSpice_voltage_output_file_lines = StringTrimLeft($LTSpice_voltage_output_file_lines, StringLen($LTSpice_voltage_output_file_lines)*$ignorance_region_of_voltage_percent/100) ; Remove some Leftmost characters from the string.
$LTSpice_voltage_output_file_lines = StringTrimRight($LTSpice_voltage_output_file_lines, 2) ; Remove the last line from the string.
;;;;;;;;;; CONVERT THE LTSPICE VOLTAGE OUTPUT (.voltage) OPENED FILE TO ARRAY ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Local $LTSpice_voltage_output_array = Build_Voltage_output_Array($LTSpice_voltage_output_file_lines, 2)
If $debuging_mode Then
_ArrayDisplay($LTSpice_voltage_output_array,'Voltage output Array')
EndIf

 ;;;;;;;;;;;;;;; READ RIPPLE AND VOLTAGE FROM LTSPICE ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Tray_Messages_Push('•  Calculating (.voltage) file ripple and mean')
         $sum = 0
	  For $i = 0 To UBound($LTSpice_voltage_output_array, 1)-1
;		 If $debuging_mode Then
;		   MsgBox(262176, "test array",  $LTSpice_voltage_output_array[$i][1],1)
;		 EndIf
		 $sum = $sum + $LTSpice_voltage_output_array[$i][1]
	  Next
$mean_voltage = $sum / UBound($LTSpice_voltage_output_array, 1)
$min_voltage = _ArrayMin($LTSpice_voltage_output_array, 1, -1,-1,1)
$max_voltage = _ArrayMax($LTSpice_voltage_output_array, 1, -1,-1,1)
If $debuging_mode Then
     If FileExists ( @ScriptDir & "\" & "filtered_(considered)_data_range.voltage" ) Then
	    If Not FileDelete ( @ScriptDir & "\" & "filtered_(considered)_data_range.voltage" ) Then
			MsgBox(262160, "[post_processing] " & $cst_project_file_name, "There was an error deleting the existing Considered Current Range (.voltage) file. @error: " & @error , 20) ; An error occurred reading the current script file.
	    EndIf
	 EndIf
	    If Not FileWrite( @ScriptDir & "\" & "filtered_(considered)_data_range.voltage" ,_ArrayToString($LTSpice_voltage_output_array)) Then
			MsgBox(262160, "[post_processing] " & $cst_project_file_name, "There was an error writing the Considered Voltage Range (.voltage) file. @error: " & @error , 20) ; An error occurred reading the current script file.
		ContinueLoop
	    EndIf
   MsgBox(262176, "[post_processing] Voltage: No. of DATA",  (UBound($LTSpice_voltage_output_array, 1)-1) , 10)
   MsgBox(262176, "[post_processing] Voltage: Mean Value",  $mean_voltage, 1 , 10)
EndIf
        If Not FileWrite($result_summary_file , 'Voltage (Volt): ' & @CRLF &  'Min: ' & $min_voltage & @CRLF &"Max: " & $max_voltage & @CRLF & "Difference: " &$max_voltage - $min_voltage & @CRLF & "Mean Value: " & $mean_voltage & @CRLF & @CRLF ) Then
        MsgBox(262160, "[post_processing] " & $cst_project_file_name, "There was an error writing the Result Summary (.o) file. @error: " & @error,60) ; An error occurred reading the current script file.
		ContinueLoop
	    EndIf
 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
 If $draw_load_resistance Then ;;;;;;;;;;; NO NEED TO SHOW IF THERE IS NO LOAD ;;;;;;;;;;;;;;;;;;;;;;;;
 ;;;;;;;;;;;;;;;;; CALCULATING ACCELERATOR MEAN BEAM POWER ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	  If UBound($LTSpice_voltage_output_array, 1) = UBound($LTSpice_current_output_array, 1) Then
         $sum = 0
	  For $i = 0 To UBound($LTSpice_voltage_output_array, 1)-1
;		 If $debuging_mode Then
;		   MsgBox(262176, "test array",  $LTSpice_voltage_output_array[$i][1],1)
;		 EndIf
		 $sum = $sum + $LTSpice_voltage_output_array[$i][1]*$LTSpice_current_output_array[$i][1]
	  Next
$mean_beam_power = $sum / UBound($LTSpice_voltage_output_array, 1)

        If Not FileWrite($result_summary_file ,'Beam Power:' & @CRLF & 'Mean Beam Power (Watt) :' & $mean_beam_power & @CRLF & 'Used Load Resistance (Ohm) : ' & $LOAD_resistance & @CRLF & @CRLF ) Then
        MsgBox(262160, "[post_processing] " & $cst_project_file_name, "There was an error writing the Result Summary (.o) file. @error: " & @error,60) ; An error occurred reading the current script file.
		ContinueLoop
	    EndIf
	  Else
        MsgBox(262160, "[post_processing] " & $cst_project_file_name, "Beam Power calculation encountered an error." & @CRLF & "The Array size of current and voltage do not match. Can't do the multiplication.",60) ; An error occurred reading the current script file.
	  EndIf

EndIf
 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
If $give_origin_dat_file_instead_of_voltage_and_current Then  ;;;;;;;;;;;;;;;;;;; prepare and write .dat Origin input file ;;;;;;;;;;;;;;;;;
   Do
Tray_Messages_Push('•  Preparing Origin (.dat) file')
$LTSpice_voltage_output_array = 0
$LTSpice_current_output_array = 0
    If Not _FileReadToArray($LTSpice_voltage_output_file, $LTSpice_voltage_output_array, 0, @TAB) Then
        MsgBox(262160, "[origin_output] " & $cst_project_file_name, "There was an error reading the Voltage output (.voltage) file. @error: " & @error,20)
		ExitLoop
	 EndIf
$origin_dat_output_array = $LTSpice_voltage_output_array
If $draw_load_resistance Then
    If Not _FileReadToArray($LTSpice_current_output_file, $LTSpice_current_output_array, 0, @TAB) Then
        MsgBox(262160, "[origin_output] " & $cst_project_file_name, "There was an error reading the Current output (.current) file. @error: " & @error,20)
		ExitLoop
    EndIf
  ReDim $origin_dat_output_array[UBound($origin_dat_output_array)][UBound($origin_dat_output_array,2) + 1]
    For $i = 0 To UBound($origin_dat_output_array, 1)-1
        $origin_dat_output_array[$i][2] = $LTSpice_current_output_array[$i][1]
    Next
EndIf
If $debuging_mode Then
	     _ArrayDisplay($origin_dat_output_array, "origin output array") ; Display the array.
EndIf
$origin_dat_out_file_location = @ScriptDir & "\" & $cst_project_file_name & "." & $DateStr & "_origin.dat" ;;;;; THE ORIGIN OUTPUT FILE ;;;;;;;;;

        If Not _FileWriteFromArray($origin_dat_out_file_location, $origin_dat_output_array, 0, Default , @TAB) Then
        MsgBox(262160, "[origin_output] " & $cst_project_file_name, "There was an error writing the Origin Input Data (.dat) file. @error: " & @error,60)
		ContinueLoop
	    EndIf
If $draw_load_resistance Then
_FileWriteToLine($origin_dat_out_file_location, 2, '(sec)' & @TAB & '(volt)' & @TAB & '(ampere)', False)
Else
_FileWriteToLine($origin_dat_out_file_location, 2, '(sec)' & @TAB & '(volt)', False)
EndIf
_FileWriteToLine($origin_dat_out_file_location, 1, '', False)
_FileWriteToLine($origin_dat_out_file_location, 1, 'Simulation started on:' & @TAB & $DateStr, False)
_FileWriteToLine($origin_dat_out_file_location, 1, 'CST Project File Name:' & @TAB & $cst_project_file_name, False)
_FileWriteToLine($origin_dat_out_file_location, 1, 'Created automaticaly with an AutoIt code written by me: o.hassanpour@mail.sbu.ac.ir', False)
;;;;;;;; Delete output voltage and current files because they are not needed;;;;;;;;;;
FileDelete ( $LTSpice_voltage_output_file )
If $draw_load_resistance Then
FileDelete ( $LTSpice_current_output_file )
EndIf
   Until 1
EndIf
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;



Tray_Messages_Push('•  Finished!')
;If $debuging_mode Then
If $draw_load_resistance Then ;;;;;;;;;;; NO NEED TO SHOW IF THERE IS NO LOAD ;;;;;;;;;;;;;;;;;;;;;;;;
MsgBox(262176, "[Finished] ", "Current: " & @CRLF & 'Min: ' & $min_current & @CRLF &"Max: " & $max_current & @CRLF & "Difference: " &$max_current - $min_current & @CRLF & "Mean Value: " & $mean_current,15)
EndIf

MsgBox(262176, "[Finished] ", "Voltage: " & @CRLF & 'Min: ' & $min_voltage & @CRLF &"Max: " & $max_voltage & @CRLF & "Difference: " &$max_voltage - $min_voltage & @CRLF & "Mean Value: " & $mean_voltage,15)

If $draw_load_resistance Then ;;;;;;;;;;; NO NEED TO SHOW IF THERE IS NO LOAD ;;;;;;;;;;;;;;;;;;;;;;;;
MsgBox(262176, "[Finished] ", "Mean Beam Power: " & $mean_beam_power ,15)
EndIf
;EndIf

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
						Next ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

If $power_down_after_run Then ;;;;;;;;;;;;; SHUTTING DOWN AFTER RUN ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
   If MsgBox(33, "[Finished] ", "The run has been finished and the code is going to put your computer on standby after 30 secounds." & @CRLF & "Do you want to continue?",30) <> 2 Then
	  If Shutdown(64) <> 1 Then ; hibernate
		 Shutdown(32)			;if not possible: standby
	  EndIf
   EndIf
EndIf

Func Build_Capacitance_Array($capacitance_file_lines = "", $cols = 100)
    $capacitance_file_lines = StringReplace($capacitance_file_lines, @CRLF, "|")
    $capacitance_file_lines = StringReplace($capacitance_file_lines, @CR, "|")
    $capacitance_file_lines = StringReplace($capacitance_file_lines, @LF, "|")
    $capacitance_file_lines = StringSplit($capacitance_file_lines, "|", 2)
    Local $capacitance_array[1][$cols]
    Local $cell
    For $ii = 0 To UBound($capacitance_file_lines, 1) - 1
        $cell = StringSplit($capacitance_file_lines[$ii], @TAB, 2)
        ReDim $capacitance_array[UBound($capacitance_array, 1) + 1][$cols]
        For $jj = 0 To UBound($cell, 1) - 1
            $capacitance_array[$ii][$jj] = $cell[$jj]
        Next
    Next
    _ArrayDelete($capacitance_array, UBound($capacitance_array, 1) - 1)
    Return $capacitance_array
EndFunc

Func Build_Voltage_output_Array($LTSpice_voltage_output_file_lines = "", $cols = 2)
    $LTSpice_voltage_output_file_lines = StringReplace($LTSpice_voltage_output_file_lines, @CRLF, "|")
    $LTSpice_voltage_output_file_lines = StringReplace($LTSpice_voltage_output_file_lines, @CR, "|")
    $LTSpice_voltage_output_file_lines = StringReplace($LTSpice_voltage_output_file_lines, @LF, "|")
    $LTSpice_voltage_output_file_lines = StringSplit($LTSpice_voltage_output_file_lines, "|", 2)
    Local $LTSpice_voltage_output_array[1][$cols]
    Local $cell
    For $ii = 0 To UBound($LTSpice_voltage_output_file_lines, 1) - 1
        $cell = StringSplit($LTSpice_voltage_output_file_lines[$ii], @TAB, 2)
        ReDim $LTSpice_voltage_output_array[UBound($LTSpice_voltage_output_array, 1) + 1][$cols]
        For $jj = 0 To UBound($cell, 1) - 1
            $LTSpice_voltage_output_array[$ii][$jj] = $cell[$jj]
        Next
    Next
    _ArrayDelete($LTSpice_voltage_output_array, UBound($LTSpice_voltage_output_array, 1) - 1)
	_ArrayDelete($LTSpice_voltage_output_array, 0)
    Return $LTSpice_voltage_output_array
 EndFunc

Func Build_Current_output_Array($LTSpice_current_output_file_lines = "", $cols = 2)
    $LTSpice_current_output_file_lines = StringReplace($LTSpice_current_output_file_lines, @CRLF, "|")
    $LTSpice_current_output_file_lines = StringReplace($LTSpice_current_output_file_lines, @CR, "|")
    $LTSpice_current_output_file_lines = StringReplace($LTSpice_current_output_file_lines, @LF, "|")
    $LTSpice_current_output_file_lines = StringSplit($LTSpice_current_output_file_lines, "|", 2)
    Local $LTSpice_current_output_array[1][$cols]
    Local $cell
    For $ii = 0 To UBound($LTSpice_current_output_file_lines, 1) - 1
        $cell = StringSplit($LTSpice_current_output_file_lines[$ii], @TAB, 2)
        ReDim $LTSpice_current_output_array[UBound($LTSpice_current_output_array, 1) + 1][$cols]
        For $jj = 0 To UBound($cell, 1) - 1
            $LTSpice_current_output_array[$ii][$jj] = $cell[$jj]
        Next
    Next
    _ArrayDelete($LTSpice_current_output_array, UBound($LTSpice_current_output_array, 1) - 1)
	_ArrayDelete($LTSpice_current_output_array, 0)
    Return $LTSpice_current_output_array
 EndFunc

Func Tray_Messages_Push($newmessage='')
;If $debuging_mode Then
;   _ArrayDisplay($tray_messages_array, "$tray_messages_array BEFORE _ArrayPush()")
;EndIf
_ArrayPush($tray_messages_array, $newmessage,1)
If $debuging_mode Then
   _ArrayDisplay($tray_messages_array, "$tray_messages_array AFTER _ArrayPush()")
EndIf
    TraySetToolTip(_ArrayToString($tray_messages_array, @CRLF , -1, -1) & @CRLF) ; The tray menu icon must be shown before we can set some text.
EndFunc   ;==>Tray_Messages_Push